### ISSUE TITLE
Add tag v1.0.0 for the release version

### ISSUE THREAD

**Issue by igr** [apache/airflow-client-go#25]
Airflow API version is `1.0.0` (https://airflow.apache.org/docs/apache-airflow/stable/stable-rest-api-ref.html)

AFAIK, all we have to do is make a tag `v1.0.0` on the repo. This should set the client version for the Go module ([official docs](https://go.dev/doc/modules/developing#decentralized))

Of course, before that, there should be some kind of _client versioning strategy_ in place. One simple strategy is to follow the API version, so every time when you bump the API version, you rebuild the client. However, sometimes generated library needs an update (e.g due to a bug in the client generation). If this happens often, you might simply have independent versioning of the client, while you maintain at least the major version. In that case you must have a mapping table that indicates client version to api version matching.

Either way, the first version tag should be added :)

**Comment by potiuk** [comment]
I think (Again) our Airflow API tag is wrong and it should be fixed in the first place. the API version of ours should reflect Airflow Major/Minor Version at the very least - similarly as we agreed for the Python Client. Again - raising discussion at the devlist is a good start. Menoining in the issue will not move a needle.
